[main]

[[main.block]]
format = "html"
content_file = "input/elements/head.html"

[[main.block]]
format = "html"
content_file = "input/pages/index/head.html"

[[main.block]]
format = "html"
content_file = "input/elements/navbar.html"

[[main.block]]
format = "html"
content_file = "input/pages/index/index.html"

[[main.block]]
format = "html"
content_file = "input/elements/footer.html"
